name:                haskell99
version:             0.1.0.0
github:              "pbalaga/haskell99"
license:             MIT
author:              "Paweł Bałaga"
maintainer:          "-"
copyright:           "2018 Paweł Bałaga name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pbalaga/haskell99#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell99-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell99

tests:
  haskell99-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell99
    - hspec
